# h2 http://localhost:8080/h2-console
spring:
 jpa:
         database: POSTGRESQL 
 datasource: 
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/original
      username: original
      password: original
 debug: true
 image:
 local: true